# Generated by Django 5.0.14 on 2025-06-01 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_courseentry_delete_usercourse"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseentry",
            name="location",
        ),
    ]
