# Generated by Django 5.0.14 on 2025-05-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profilepage", "0002_remove_profile_photo_profile_bio_profilephoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilephoto",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
    ]
