# Generated by Django 5.0.14 on 2025-05-29 17:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="like",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="match",
            options={"ordering": ["-matched_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="match",
            unique_together={("user1", "user2")},
        ),
    ]
