# Generated by Django 5.0.14 on 2025-06-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0002_alter_like_options_alter_match_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="like",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="like",
            name="is_liked",
            field=models.BooleanField(default=True),
        ),
    ]
