# Generated by Django 5.0.14 on 2025-06-07 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0004_unmatchrecord"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UnmatchRecord",
        ),
    ]
